// Minimal Supabase Database types for the meualbum2026 project.
//
// Hand-written rather than generated by `supabase gen types typescript` so the
// repo stays self-contained. If/when more tables are added, run the CLI and
// drop the generated file in here instead.

export type Database = {
  public: {
    Tables: {
      teams: {
        Row: {
          code: string
          name_key: string
          flag: string
          conf: string
          group_letter: string | null
          sort_order: number
        }
        Insert: Database['public']['Tables']['teams']['Row']
        Update: Partial<Database['public']['Tables']['teams']['Row']>
      }
      stickers_catalog: {
        Row: {
          id: string
          team_code: string
          number: number
          player_name: string | null
          is_special: boolean
          sort_order: number
        }
        Insert: Database['public']['Tables']['stickers_catalog']['Row']
        Update: Partial<Database['public']['Tables']['stickers_catalog']['Row']>
      }
      user_stickers: {
        Row: {
          user_id: string
          sticker_id: string
          quantity: number
          updated_at: string
        }
        Insert: {
          user_id: string
          sticker_id: string
          quantity?: number
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['user_stickers']['Insert']>
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      adjust_sticker: {
        Args: { p_sticker_id: string; p_delta: number }
        Returns: number
      }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

// ── Domain aliases used across the app ──────────────────────────────────────
export type Team             = Database['public']['Tables']['teams']['Row']
export type CatalogSticker   = Database['public']['Tables']['stickers_catalog']['Row']
export type UserSticker      = Database['public']['Tables']['user_stickers']['Row']
export type Sticker          = CatalogSticker & { quantity: number }
